---
- hosts:
    #- wispro
    - nat_servers
  become: true
  gather_facts: no
  tasks:
    - name: Install crontab line for get_address script
      ansible.builtin.cron:
        name: "ADD get_address.php script"
        state: present
        job: "/usr/bin/php /opt/notificaciones/command_portal/get_address.php"
    - name: Get Address execution
      ansible.builtin.shell: /usr/bin/php /opt/notificaciones/command_portal/get_address.php

